### ISSUE TITLE
Do we need a MolecularSystemNeeded error?

### ISSUE THREAD

**Issue by dprada** [uibcdf/MolSysMT#64]
In @Daniel-Ibarrola's PR the following code in `basic/set.py`:

```python
    if check:

        if not is_molecular_system(molecular_system):
            raise MolecularSystemNeeded()
```

was replaced by:

```python
    if check:

        if not is_molecular_system(molecular_system):
            raise TypeError("A molecular system is needed.")
```

I gues that at this point, the version of current process should be something as:

```python
    if check:
        digest_single_molecular_system(molecular_system)
```

And it is inside the digestion where the error should be raised. This needs to be reviewed. Do we already have a MolecularSystemNeeded error to be raised in this situation?

**Comment by Daniel-Ibarrola** [comment]
This was fixed by #71. The `molecular_system` argument is checked by digestion function and it raises a MolecuarSystemNedeed error in case the argument doesn't have the expected type.
